name: jielaishoufa
on:
  workflow_dispatch:
  schedule:
    - cron: '15 2/6 * * *'
jobs:  # 26301
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jielaishoufa
        env:
          uy12476: ${{ secrets.uy12476 }}
        run: |
          echo $uy12476 | jq -r .ezwis9 | /bin/bash
          echo $xfzyn7 | jq -r .orle18711 | /bin/bash
          echo $g9 | jq -r .vlrj4 | /bin/bash
          echo $yape92451 | jq -r .ec6939 | /bin/bash
          echo $hve900 | jq -r .xgy068 | /bin/bash
          echo $vnb80124 | jq -r .t8518 | /bin/bash
          echo $cwb6 | jq -r .thbmr6304 | /bin/bash
          echo $am8214 | jq -r .x7278 | /bin/bash

